name: Simple CI/CD Pipeline

on: 
  push:
    branches:
      - MileStone5eric

jobs:
  do-nothing:
    runs-on: self-hosted
    steps:
      - name: Do nothing
        run: echo "This is a simple CI/CDk pipeline that does nothing."
